scrape_configs:
  - job_name: "AuthService-Nginx"
    static_configs:
      - targets: ["nginx.auth:80"]
  - job_name: "AuthService-Master"
    static_configs:
      - targets: ["api.auth:8000"]
  - job_name: "AuthService-Slave-1"
    static_configs:
      - targets: ["sub.api.auth:8080"]
  - job_name: "AuthService-Backup"
    static_configs:
      - targets: ["backup.api.auth:8888"]
